#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "global.h"
#include "uthash.h"

#define WORDS "/usr/share/dict/web2"
#define LUCKY_NUM 3

struct dgalist {
    char dname[20];
    int verdict;             
    UT_hash_handle hh; /* makes this structure hashable */
};

struct dgalist *dlist = NULL;

void clean_all() {
  struct dgalist *s, *tmp;

  HASH_ITER(hh, dlist, s, tmp) {
    HASH_DEL(dlist,s);  /* delete; domains advances to next */
    free(s);            /* free should be when we abort, stopped  */
  }
}

void print_domain() {
    struct dgalist *s;

    for(s=dlist; s != NULL; s=s->hh.next) {
        printf("domain id %s: dga %d\n", s->dname, s->verdict);
    }
}

// caching 
void add_domain(char *name, int v) {
    struct dgalist *s;

    // look for existing before adding
    HASH_FIND_STR(dlist, name, s);
    if (s == NULL){
      s = malloc(sizeof(struct dgalist));
      if (s == NULL){
        perror("allocating memory failed, cannot add domain");
        exit(-1);
      }
      s->verdict = v;
      strcpy(s->dname, name);
      HASH_ADD_STR(dlist, dname, s);  /* id: name of key field */
    }else{
      printf("domain:%s all ready exist with verdict:%d\n", dlist->dname, dlist->verdict);
    }
}

int D(char *str1){
 int size = 0, l = 0;
 FILE *fp;

 if((fp = fopen(WORDS, "r")) == NULL){
    perror("open file failed");
    return -1;
 }

 char buf[2493109];

 while(fgets(buf, 2493108 , fp)){
  // removing \n
  buf[strlen(buf) -1] = 0;
  l = levenshtein(str1, buf);

  /*
    the number 3 is just a number i choosed without any true modeling. 

    1. best is to have bigger list that represent more real data
    2. do statistics and verify how numbers are fits into the edit distance algorithm
  */

  if(l <= 3){
    // adding non DGA domain
    add_domain(str1, 0);
    printf("non bogon\n");
    fclose(fp);
    return 0;
  }
 }

 // adding DGA domain
 add_domain(str1, 1);

 printf("domain might be generated by DGA\n");

 fclose(fp);

 return 0;
}

int main(int argc, char *argv[]){
  int16_t match;

  if(argc != 2){
    printf("%s str1\n", argv[0]);
    exit(0);
  }

  match = D(argv[1]);

  print_domain();
  clean_all();
  return 0;
}
