/*
___________      ____               
\__    ___/____ /_   | ____   ____  
  |    |  \__  \ |   |/  _ \ /    \ 
  |    |   / __ \|   (  <_> )   |  \
  |____|  (____  /___|\____/|___|  /
               \/                \/ 

Copyright (c) 2016, Ehud Shamir 
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/  

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "global.h"
#include "uthash.h"

#define WORDS "/usr/share/dict/web2"
#define LUCKY_NUM 3

struct dgalist {
    char dname[20];
    int verdict;             
    UT_hash_handle hh; /* makes this structure hashable */
};

struct dgalist *dlist = NULL;

void clean_all() {
  struct dgalist *s, *tmp;

  HASH_ITER(hh, dlist, s, tmp) {
    HASH_DEL(dlist,s);  /* delete; domains advances to next */
    free(s);            /* free should be when we abort, stopped  */
  }
}

/*
  this function should be called only when you need to verfy your db, not on regular bassis
*/

void print_domain() {
    struct dgalist *s;

    for(s=dlist; s != NULL; s=s->hh.next) {
        printf("domain id %s: dga %d\n", s->dname, s->verdict);
    }
}

struct dgalist *check_existing(char *name) {
    struct dgalist *s;

    HASH_FIND_STR(dlist, name, s );  /* s: output pointer */
    return s;
}

// caching 
int add_domain(char *name, int v) {
    struct dgalist *s;

    s = malloc(sizeof(struct dgalist));
    if (s == NULL){
      perror("allocating memory failed, cannot add domain");
      return -1;
    }
    s->verdict = v;
    strcpy(s->dname, name);
    HASH_ADD_STR(dlist, dname, s);  /* id: name of key field */

    return 0;
}

int D(char *str1){
 int size = 0, l = 0;
 FILE *fp;

 if((fp = fopen(WORDS, "r")) == NULL){
    perror("open file failed");
    return -1;
 }

 //  this needs to be changed to dynamic allocation
 char buf[2493109];

 while(fgets(buf, 2493108 , fp)){
  // removing \n
  buf[strlen(buf) -1] = 0;
  l = levenshtein(str1, buf);

  /*

    the number 3 is just a number i choosed without any true modeling. 

    1. best is to have bigger list that represent more real data
    2. use statistics and verify how numbers fit into the edit distance algorithm

  */

  if(l <= 3){
    // adding non DGA domain
    add_domain(str1, 0);
    printf("non bogon\n");
    fclose(fp);
    return 0;
  }
 }

 // adding DGA domain
 add_domain(str1, 1);

 printf("domain might be generated by DGA\n");

 fclose(fp);

 return 0;
}

int main(int argc, char *argv[]){

  struct dgalist *s;

  int16_t match;

  if(argc != 2){
    printf("%s str1\n", argv[0]);
    exit(0);
  }

  // check if we have cached the name before //
  s = check_existing(argv[1]);
  if(s == NULL){
    match = D(argv[1]);
  }
  else{
     printf("name:%s verdict:%d\n", s->dname, s->verdict);
  }

  print_domain();

  // free all allocations //
  clean_all();
  return 0;
}
